Gallery implementation
bgabriel998/SoftwareDevProject pull request #100
Opened 2021-04-06 15:59 UTC by aolsson711

- Thumbnails in gallery (Hardcoded with image from resources)
- New activity for when pressing a thumbnail, to view full screen of image)

TODO comments added for changing from getting images from resource to using paths, that also will be used when taking pictures with the camera.

2021-04-07 07:43 UTC, giommok approved these changes
Seems good.

2021-04-07 21:33 UTC, magangloff requested changes
Some few changes to be made for the gallery to be properly displayed

2021-04-07 21:33 UTC, magangloff commented on app/src/main/res/layout/activity_gallery.xml
> +        android:layout_height="wrap_content"
Change layout height to display all the images at the end of the gallery.
I don't know why, but it seems like Top to bottom of the toolbar is not enough to make gallery start after toolbar, thus I added paddingTop with the height of the toolbar
```suggestion
        android:layout_height="match_parent"
        android:paddingTop="80dp"
```

2021-04-07 21:33 UTC, magangloff commented on app/src/main/res/layout/activity_gallery.xml
> +        app:layout_constraintEnd_toEndOf="parent"
End to end constraint can be removed
```suggestion

```

2021-04-07 21:33 UTC, magangloff commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/GalleryAdapter.java
> +    private Context mContext;
mContext can be made final
```suggestion
    private final Context mContext;    
```

2021-04-07 21:33 UTC, magangloff commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/GalleryAdapter.java
> +    private List<Integer> images;
images can be made final
```suggestion
    private final List<Integer> images;
```

2021-04-07 21:33 UTC, magangloff commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/GalleryAdapter.java
> +    public class ViewHolder extends RecyclerView.ViewHolder {
Class Viewholder can be made static
```suggestion
    public static class ViewHolder extends RecyclerView.ViewHolder {
```

2021-04-07 21:33 UTC, magangloff commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/GalleryAdapter.java
> +        private ImageView image;
image can be made final
```suggestion
        private final ImageView image;
```

2021-04-08 13:52 UTC, magangloff requested changes
Place toolbar after the recyclerView to use the back button.

2021-04-08 13:52 UTC, magangloff commented on app/src/main/res/layout/activity_gallery.xml
> +        app:layout_constraintTop_toBottomOf="@+id/toolbar"/>
Place the toolbar after the RecyclerView to make sure that the recyclerView does not overdraw the toolbar and makes the back button not usable. This makes the test TestToolbarBackButton fail.
```suggestion
</androidx.constraintlayout.widget.ConstraintLayout> 
    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/gallery_recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingTop="80dp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/toolbar"/>
        
        <!-- Toolbar -->
        <include layout="@layout/toolbar"/>
```

2021-04-09 13:00 UTC, magangloff approved these changes

2021-04-09 13:00 UTC, merged