User point static
bgabriel998/SoftwareDevProject pull request #168
Opened 2021-04-27 22:31 UTC by ravifrancesco

Made the UserPoint class a singleton class. Now it's accessible through the static method `UserPoint.getInstance(Context mContext)`. 

Adapted tests accordingly

2021-04-28 15:55 UTC, magangloff requested changes
Small comment for the test, else all good.

2021-04-28 15:55 UTC, magangloff commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/points/ComputePOIPointsTest.java
> +        userPoint.setLocation(46.519251915333676, 6.558563221333525, 220, 0);
You could rechange location to the mont-blanc and change the altitude or maybe change the comment above

2021-04-28 15:59 UTC, bgabriel998 approved these changes
Change magic numbers for constants. 
Otherwise the code is fine. The singleton is a good decision

2021-04-28 15:59 UTC, bgabriel998 commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/points/GeonamesHandlerTest.java
> +                0);
Error in function call, third parameter should be altitude
```suggestion
        userPoint.setLocation(MOCK_LOCATION_LAT_LAUSANNE,
                MOCK_LOCATION_LON_LAUSANNE,
                MOCK_LOCATION_ALT_LAUSANNE,
                0);
```

2021-04-28 15:59 UTC, bgabriel998 commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/points/GeonamesHandlerTest.java
> +        userPoint.setLocation(46.519251915333676, 6.558563221333525, 220, 0);
Use constants instead
```suggestion
        userPoint.setLocation(MOCK_LOCATION_LAT_LAUSANNE, MOCK_LOCATION_LON_LAUSANNE, MOCK_LOCATION_ALT_LAUSANNE, 0);
```

2021-04-28 15:59 UTC, bgabriel998 commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/points/GeonamesHandlerTest.java
> +        userPoint.setLocation(46.519251915333676, 6.558563221333525, 220, 0);
Use constants instead
```suggestion
        userPoint.setLocation(MOCK_LOCATION_LAT_LAUSANNE, MOCK_LOCATION_LON_LAUSANNE, MOCK_LOCATION_ALT_LAUSANNE, 0);
```

2021-04-28 15:59 UTC, bgabriel998 commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/points/GeonamesHandlerTest.java
> +        userPoint.setLocation(46.519251915333676, 6.558563221333525, 220, 0);
Use constants instead
```suggestion
        userPoint.setLocation(MOCK_LOCATION_LAT_LAUSANNE, MOCK_LOCATION_LON_LAUSANNE, MOCK_LOCATION_ALT_LAUSANNE, 0);
```

2021-04-28 15:59 UTC, bgabriel998 commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/points/ComputePOIPointsTest.java
> +        userPoint = UserPoint.getInstance(mContext); // TODO check if working properly
Remove TODO

```suggestion
        userPoint = UserPoint.getInstance(mContext); 
```

2021-04-29 08:16 UTC, bgabriel998 approved these changes

2021-04-29 08:22 UTC, magangloff requested changes
```single_instance``` in UserPoint was never updated and thus always ```null```. This should be updated.

2021-04-29 08:22 UTC, magangloff commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/points/UserPoint.java
> +        return single_instance;
Can be changed for better readability:
```suggestion
        return single_instance == null ? new UserPoint(mContext) : single_instance;
```

2021-04-29 08:22 UTC, magangloff commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/points/UserPoint.java
> +    private static final UserPoint single_instance = null; // singleton instance
Should not be made final to assign a variable to single_instance
```suggestion
    private static UserPoint single_instance = null; // singleton instance
```

2021-04-29 08:22 UTC, magangloff commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/points/UserPoint.java
>      }
```single_instance``` should be assigned here, else ```single_instance``` is always ```null```
```suggestion
        single_instance = this;
    }
```

2021-04-29 09:16 UTC, magangloff approved these changes

2021-04-29 11:17 UTC, merged