Improve map and implement settings
bgabriel998/SoftwareDevProject pull request #172
Opened 2021-04-29 19:43 UTC by bgabriel998

# Improvements made on map 
Added two buttons on map, one to zoom on user location and one to change map provider from default to satellite.

# Implement settings 
Add few settings in settings activity using shared preferences. 
Language preferences is already working for the french translation.
**See image bellow :** 
![image](https://user-images.githubusercontent.com/72859273/116608682-c6e11c80-a933-11eb-82ba-0213a1083b6a.png)

2021-04-29 20:29 UTC, giommok commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/general/SettingsActivityTest.java
> +<<<<<<< HEAD:app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/SettingsActivityTest.java
```suggestion

```

2021-04-29 20:30 UTC, giommok commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/general/SettingsActivityTest.java
> +=======
```suggestion

```

2021-04-29 20:30 UTC, giommok commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/general/SettingsActivityTest.java
> +>>>>>>> master:app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/general/SettingsActivityTest.java
```suggestion
```

2021-04-29 20:35 UTC, giommok commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/general/SettingsActivityTest.java
> +<<<<<<< HEAD:app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/SettingsActivityTest.java
```suggestion
```

2021-04-29 21:06 UTC, giommok requested changes
Code looks good! 
However, I made some comments about minor things (like importing all the constants at once instead of importing every single constant) and if I'm correct you forgot Italian in the language choice.

2021-04-29 21:06 UTC, giommok commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/general/SettingsActivity.java
> +    public void setLocale(String lang) {
It's quite hard to understand what happens inside this method. Maybe it would be better to add some more comments?

2021-04-29 21:06 UTC, giommok commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/map/OSMMap.java
> +            String[] urlArray = {"http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/"};
Should we put this string in a constant?

2021-04-30 08:14 UTC, giommok approved these changes

2021-04-30 08:39 UTC, magangloff requested changes
Suggested some changes, there are some errors in the tests that need to be looked at

2021-04-30 08:39 UTC, magangloff commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/map/OSMMapTest.java
> +        assertEquals(TestingConstants.TILE_SCALING_FACTOR, mapView.getTilesScaleFactor(),0.0f);
Yes, but the constants need to be made public first

2021-04-30 08:39 UTC, magangloff commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/TestingConstants.java
> +    static final double MOCK_LOCATION_ALT_LAUSANNE = 220;
Constants should be made public.
```suggestion
    public static final float TILE_SCALING_FACTOR = 1.5f;

    //Constants POI names
    public static final String MONT_BLANC_NAME = "Mont Blanc - Monte Bianco";
    public static final String DENT_DU_GEANT_NAME = "Dent du Geant";
    public static final String POINTE_DE_LAPAZ_NAME = "Pointe de Lapaz";
    public static final String AIGUILLE_DU_PLAN = "Aiguille du Plan";
    //Constants POI coordinates
    public static final double MONT_BLANC_LAT = 45.8325;
    public static final double MONT_BLANC_LONG = 6.8641666666667;
    public static final double MONT_BLANC_ALT = 4810;

    public static final double DENT_DU_GEANT_LAT = 45.86355980599387;
    public static final double DENT_DU_GEANT_LONG = 6.951348205683087;
    public static final double DENT_DU_GEANT_ALT = 4013;

    public static final double AIGUILLE_DU_PLAN_LAT = 45.891667;
    public static final double AIGUILLE_DU_PLAN_LONG = 6.907222;
    public static final double AIGUILLE_DU_PLAN_ALT = 3673;

    public static final double POINTE_DE_LAPAZ_LAT = 45.920774986207014;
    public static final double POINTE_DE_LAPAZ_LONG = 6.812914656881065;
    public static final double POINTE_DE_LAPAZ_ALT = 3660;

    //Geonames Handler testing constants
    public static final int MILLI_SEC_TO_SEC = 1000;
    public static final int DEFAULT_QUERY_MAX_RESULT = 300;
    public static final int DEFAULT_QUERY_TIMEOUT = 10;
    public static final int GIVEN_RANGE_IN_KM = 20;
    public static final int GIVEN_QUERY_MAX_RESULT = 30;
    public static final int GIVEN_QUERY_TIMEOUT = 10;

    public static final double MOCK_LOCATION_LAT_LAUSANNE = 46.519251915333676;
    public static final double MOCK_LOCATION_LON_LAUSANNE = 6.558563221333525;
    public static final double MOCK_LOCATION_ALT_LAUSANNE = 220;
```

2021-04-30 08:39 UTC, magangloff commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/map/OSMMapTest.java
Missing import. 
```suggestion
    import com.github.bgabriel998.softwaredevproject.R;
```

2021-04-30 08:41 UTC, bgabriel998 commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/TestingConstants.java
> +    static final double MOCK_LOCATION_ALT_LAUSANNE = 220;
Resolved in commit

2021-04-30 08:41 UTC, bgabriel998 commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/map/OSMMapTest.java
Resolved in commit

2021-04-30 09:04 UTC, magangloff requested changes
A few changes requested, constants can be imported in one line as Giovanni suggested.

2021-04-30 09:10 UTC, bgabriel998 commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/map/OSMMap.java
> +            changeMapTileSourceButton.setBackground(context.getResources().getDrawable(R.drawable.button_bg_round_white));
Resolved in commit

2021-04-30 09:10 UTC, bgabriel998 commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/map/MapActivity.java
> +        });
Resolved in commit

2021-04-30 09:10 UTC, bgabriel998 commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/map/MapActivity.java
> +        });
Resolved in commit

2021-04-30 09:11 UTC, bgabriel998 commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/general/SettingsActivity.java
> +    };
Resolved in commit

2021-04-30 09:11 UTC, bgabriel998 commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/general/SettingsActivity.java
> +        Locale locale = new Locale("en");
Resolved in commit

2021-04-30 09:11 UTC, bgabriel998 commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/general/SettingsActivity.java
> +        conf.locale = myLocale;
Resolved in commit

2021-04-30 09:11 UTC, bgabriel998 commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/map/OSMMapTest.java
> +    public void pressSatelliteNormalMapButton() throws InterruptedException {
Resolved in commit

2021-04-30 09:24 UTC, magangloff requested changes
Seems all good, one question regarding the persistency of the settings. When changing the settings (for example english to french) and then closing and reopening the app, the language will be English again but will be marked as french in the settings. Maybe we should check all the settings in the initActivity and set the parameters accordingly.

But that will probably need to be done in another task or what do you think?

2021-04-30 10:43 UTC, magangloff approved these changes

2021-04-30 10:43 UTC, merged