Add storage class
bgabriel998/SoftwareDevProject pull request #196
Opened 2021-05-06 15:48 UTC by magangloff

Addressed some points pointed out by the TAs:
- Added a StorageHandler that stores and retrieves files. Currently only contains methods for the pictures but can be extended with methods for other files.
- Added an ImageHandler that handles the rotating of the images for the gallery.
- Added HttpClient for the download of the topography map

2021-05-06 18:04 UTC, bgabriel998 requested changes
Minor changes requested

2021-05-06 18:04 UTC, bgabriel998 commented on app/src/main/java/ch/epfl/sdp/peakar/points/HttpClientTopographyMap.java
> +            if (response.getStatusLine().getStatusCode() == 200) {
Change `200` for a meaningful constant name

2021-05-06 18:04 UTC, bgabriel998 commented on app/src/main/java/ch/epfl/sdp/peakar/points/HttpClientTopographyMap.java
> +     *
Add `@return` in javadoc

2021-05-06 18:04 UTC, bgabriel998 commented on app/src/main/java/ch/epfl/sdp/peakar/utils/StorageHandler.java
> +        int quality = 100;
A comment explaining quality could be added here

2021-05-06 18:04 UTC, bgabriel998 commented on app/src/main/java/ch/epfl/sdp/peakar/utils/StorageHandler.java
> +     */
Add `@param` to javadoc

2021-05-06 18:04 UTC, bgabriel998 commented on app/src/main/java/ch/epfl/sdp/peakar/utils/StorageHandler.java
> +     * Returns outpudirectory to store images. Use externel media if it is available, our app's
```suggestion
     * Returns outpudirectory to store images. Use external media if it is available, our app's
```

2021-05-06 20:25 UTC, bgabriel998 approved these changes

2021-05-07 09:01 UTC, ravifrancesco approved these changes
Good job, it seems more maintainable and easier to modify now

2021-05-07 10:19 UTC, merged