User profile
bgabriel998/SoftwareDevProject pull request #219
Opened 2021-05-11 20:27 UTC by aolsson711

- Created the new profile activity. 
- No functionality added, only buttons add hide correct buttons
- No tests added since functionality will create meaningful tests.

closes #199

2021-05-12 16:06 UTC, bgabriel998 reviewed
Good one. Small modifications requested before merging.

2021-05-12 16:06 UTC, bgabriel998 commented on app/src/main/java/ch/epfl/sdp/peakar/user/profile/NewProfileActivity.java
> +        String profileText = "Score: " + UIUtils.IntegerConvert(points);
Use string ressources for translations

2021-05-12 16:06 UTC, bgabriel998 commented on app/src/main/java/ch/epfl/sdp/peakar/user/profile/NewProfileActivity.java
> +     * @param friends
Parameters description ?

2021-05-12 16:06 UTC, bgabriel998 commented on app/src/main/java/ch/epfl/sdp/peakar/utils/UIUtils.java
> +     */
Parameter dscription is missing
```suggestion
     * @param number. Integer number to convert to string
     */
```

2021-05-13 00:14 UTC, giommok reviewed
Good job!
I left a comment because I noticed you have created a `UIUtils` class and I thought that maybe we could add a short JavaDoc comment to explain what we should put in there.

2021-05-13 00:14 UTC, giommok commented on app/src/main/java/ch/epfl/sdp/peakar/utils/UIUtils.java
> +public class UIUtils {
Even if the name is quite self-explanatory, should we add a brief description of this class?

2021-05-13 10:28 UTC, giommok approved these changes

2021-05-13 10:30 UTC, bgabriel998 requested changes
Following files decrease the coverage by 3%... 
![image](https://user-images.githubusercontent.com/72859273/118113678-e0c83800-b3e6-11eb-858b-d328349ef95c.png)



--> EDIT  : resolved on discord

2021-05-13 19:57 UTC, bgabriel998 approved these changes

2021-05-13 19:59 UTC, bgabriel998 commented
The test coverage is decreased but will be improved as soon as the new UI will be implemented with real data. Yet only mock data is used

2021-05-13 20:19 UTC, merged