Loading bar
bgabriel998/SoftwareDevProject pull request #229
Opened 2021-05-13 22:27 UTC by ravifrancesco

The `SettingsMapActivity` has now a new GUI, using the toolbar and the color palette used in the app.

When a long-press is performed, the touch will be disabled during the download, and a loading circle will be displayed. When the download is terminated the user will be prompted to the Set`tingActiivty.`

2021-05-13 22:35 UTC, giommok requested changes
Seems good to me.
However, I think there are some tests descriptions that need to be updated, check my comments, please.

2021-05-13 22:35 UTC, giommok commented on app/src/androidTest/java/ch/epfl/sdp/peakar/general/SettingsMapActivityTest.java
>      /* Test that the "OK" button appears after adding a pin to the map */
I think this comment is outdated looking at the changes, is it correct?

2021-05-13 22:35 UTC, giommok commented on app/src/androidTest/java/ch/epfl/sdp/peakar/general/SettingsMapActivityTest.java
>      /* Tests that the activity is terminated after the ok button is pressed. */
Comment outdated.

2021-05-13 22:57 UTC, giommok approved these changes

2021-05-14 07:09 UTC, magangloff reviewed
looks all good and much cleaner than before. Just a question, what happens if the user uses his back button to exit the download, will the download be cancelled or continued in the background?

2021-05-14 07:16 UTC, ravifrancesco commented
> looks all good and much cleaner than before. Just a question, what happens if the user uses his back button to exit the download, will the download be cancelled or continued in the background?

You cannott press the back button, as touchscreen is disabled during the download

2021-05-14 07:21 UTC, magangloff commented
> > looks all good and much cleaner than before. Just a question, what happens if the user uses his back button to exit the download, will the download be cancelled or continued in the background?
> 
> You cannot press the back button, as touchscreen is disabled during the download

Well yes, you actually can, by using your back buttons from the phone(like swipe gestures for example or the android back buttons)

2021-05-14 07:24 UTC, ravifrancesco commented
> > > looks all good and much cleaner than before. Just a question, what happens if the user uses his back button to exit the download, will the download be cancelled or continued in the background?
> > 
> > 
> > You cannot press the back button, as touchscreen is disabled during the download
> 
> Well yes, you actually can, by using your back buttons from the phone(like swipe gestures for example or the android back buttons)

Oh I see, I will work on that as a task for the next sprint there

2021-05-14 07:53 UTC, magangloff approved these changes
Now, the user is forced to stay on the download activity when he starts a download. I'm not sure if this should be handled like that.

2021-05-14 07:58 UTC, ravifrancesco commented
> Now, the user is forced to stay on the download activity when he starts a download. I'm not sure if this should be handled like that.

I think it should be like this: this way the user knows when the download is running (so the user will not close the app or try to change settings while the download is running)

2021-05-14 08:44 UTC, merged