User interaction improvements
bgabriel998/SoftwareDevProject pull request #284
Opened 2021-06-02 13:59 UTC by giommok

# User interaction
- Improved the user interface with loading dialogues while a profile is being loaded.
- Improved the app response when no connection is available. Now it is way more robust. In addition, the profile of the user is no more available for a user that is offline (the usual error message is shown). But one could say that by pressing the back button you would still be able to go to the profile if it was already loaded before the connection was down. Yes, it's possible indeed. But in this case, error messages would be shown upon pressing the buttons to add friends/remove friends/change username, exactly as before.

# Backend

- Improved how the account was loaded when starting the app. Now, a check of the connection is done first. If the connection is available, the account is loaded. Otherwise, it is not (and, in case the connection returns, the auth account data will be retrieved after pressing the profile button).
- The account data retrieval in the `InitActivity` is **not asynchronous** anymore. Thus, if the user was already authenticated and has an internet connection, the account data will be retrieved before the `InitActivity` is dispatched.

# Tests
Improved some tests and moved the widely used mock user creation methods to a separate utility class (as, before, they were located in the `AuthAccountTest` class).

2021-06-02 20:26 UTC, bgabriel998 approved these changes
Approved, nothing to say here 👍

2021-06-03 08:27 UTC, magangloff requested changes
Nice improvements, added just some small suggestions for code readability.

2021-06-03 08:27 UTC, magangloff commented on app/src/main/java/ch/epfl/sdp/peakar/general/InitActivity.java
> +
mContext is not used and can be removed.
```suggestion

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
```

2021-06-03 08:27 UTC, magangloff commented on app/src/main/java/ch/epfl/sdp/peakar/user/profile/ProfileLauncherActivity.java
> +                    });
Can be replaced by lambda expression.
```suggestion
                    .setPositiveButton("Ok", (dialog, id) -> finish());
```

2021-06-03 10:33 UTC, magangloff approved these changes

2021-06-03 10:33 UTC, merged