UI dynamic collectable
bgabriel998/SoftwareDevProject pull request #85
Opened 2021-03-30 06:36 UTC by aolsson711

Created so the collected item list in collection is dynamically loaded, where each button starts an activity with the correct information. 

closes #79

2021-03-30 08:24 UTC, giommok requested changes

2021-03-30 08:24 UTC, giommok commented on app/src/androidTest/java/com/github/bgabriel998/softwaredevproject/CollectionActivityTest.java
> +    public void TestContentOfListView(){
When we will display the actual data this test will have to be reworked, right? Maybe we should add a TODO comment? Also, what will we display when no internet connection is available? Maybe we can test this case as of now.

2021-03-30 11:59 UTC, giommok approved these changes
Looks good!

2021-04-01 09:10 UTC, magangloff requested changes

2021-04-01 09:10 UTC, magangloff commented on app/src/main/java/com/github/bgabriel998/softwaredevproject/CollectionListAdapter.java
> +    public CollectionListAdapter(Context context, int resource, List<CollectedItem> items)
Add javadoc for constructor, curly braces are not consistent

2021-04-01 13:36 UTC, aolsson711 commented on app/src/main/res/layout/collected_item.xml
>      <RelativeLayout
Needed for tests

2021-04-01 13:36 UTC, aolsson711 commented on app/src/main/res/layout/ranking_item.xml
>  <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Needed for tests

2021-04-02 06:19 UTC, magangloff approved these changes
All good

2021-04-02 06:19 UTC, merged